#!/usr/bin/env bash
# spike/run-spike.sh — Phase 0/1/2 feasibility script
#
# Tests the PCC m68k compilation pipeline through to MacBinary output.
#
# Phase 0: PCC compiles hello.c → m68k ELF (proves compiler works)
# Phase 1: Retro68 Elf2Mac links the ELF → MacBinary (proves full pipeline)
# Phase 2: Compile + link hello_toolbox.c with libtoolbox-stubs → MacBinary
#           (proves A-trap stubs bridge C cdecl → Mac ROM correctly)
#
# Usage:
#   bash spike/run-spike.sh setup            # extract Retro68 stubs from Docker, clone PCC
#   bash spike/run-spike.sh build-pcc        # build PCC for m68k code generation
#   bash spike/run-spike.sh compile          # Phase 0: compile hello.c with PCC → ELF
#   bash spike/run-spike.sh link             # Phase 1: link ELF → MacBinary via Elf2Mac
#   bash spike/run-spike.sh verify           # Phase 1: validate MacBinary header
#   bash spike/run-spike.sh build-stubs      # Phase 2: assemble libtoolbox-stubs.a
#   bash spike/run-spike.sh compile-toolbox  # Phase 2: compile hello_toolbox.c → ELF
#   bash spike/run-spike.sh link-toolbox     # Phase 2: link toolbox ELF → MacBinary
#   bash spike/run-spike.sh verify-toolbox   # Phase 2: validate toolbox MacBinary header
#   bash spike/run-spike.sh compare          # compare vs Retro68 reference (local only)
#   bash spike/run-spike.sh all              # run all phases end-to-end

set -euo pipefail
SPIKE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PCC_SRC="${SPIKE_DIR}/pcc-src"      # git clone of PCC goes here
STUBS_DIR="${SPIKE_DIR}/retro68-stubs"
HEADERS_DIR="${SPIKE_DIR}/retro68-headers"
BUILD_DIR="${SPIKE_DIR}/build"
RETRO68_IMAGE="ghcr.io/autc04/retro68:latest"

# ── setup ──────────────────────────────────────────────────────────────────
cmd_setup() {
  echo "=== Extracting Retro68 stubs from Docker image ==="
  docker pull "${RETRO68_IMAGE}"
  mkdir -p "${STUBS_DIR}" "${HEADERS_DIR}"

  # Use --entrypoint /bin/bash to bypass the Retro68 docker-entrypoint.sh,
  # which prints "Using multiversal interfaces" to stdout and corrupts the
  # tar stream when piped.  tar -h dereferences symlinks (libInterface.a
  # is a relative symlink pointing outside the lib/ directory).
  docker run --rm --entrypoint /bin/bash "${RETRO68_IMAGE}" \
    -c 'tar -hcf - -C /Retro68-build/toolchain/m68k-apple-macos lib' \
    | tar -xf - --strip-components=1 -C "${STUBS_DIR}"

  docker run --rm --entrypoint /bin/bash "${RETRO68_IMAGE}" \
    -c 'tar -hcf - -C /Retro68-build/toolchain/m68k-apple-macos include' \
    | tar -xf - --strip-components=1 -C "${HEADERS_DIR}"

  echo "Stubs extracted to: ${STUBS_DIR}"
  echo "Headers extracted to: ${HEADERS_DIR}"

  if [ ! -d "${PCC_SRC}" ]; then
    echo "=== Cloning PCC ==="
    git clone https://github.com/IanHarvey/pcc "${PCC_SRC}"
  fi
}

# ── build-pcc ──────────────────────────────────────────────────────────────
cmd_build_pcc() {
  echo "=== Building PCC ccom for m68k code generation ==="
  if [ ! -d "${PCC_SRC}" ]; then
    echo "ERROR: ${PCC_SRC} not found — run 'bash spike/run-spike.sh setup' first" >&2
    exit 1
  fi
  pushd "${PCC_SRC}" > /dev/null

  # PCC's configure.ac maps target_os=apple → abi=classic68k → m68k backend.
  # config.sub (2015) treats 'apple' as a vendor alias (not OS) and rejects
  # the triple before configure.ac runs.  Pre-populate config.cache so
  # AC_CANONICAL_TARGET uses the cached values and skips config.sub.
  BUILD_TRIPLE=$(gcc -dumpmachine 2>/dev/null || echo "x86_64-unknown-linux-gnu")
  cat > config.cache << EOF
ac_cv_build=${BUILD_TRIPLE}
ac_cv_build_alias=${BUILD_TRIPLE}
ac_cv_host=${BUILD_TRIPLE}
ac_cv_host_alias=${BUILD_TRIPLE}
ac_cv_target=m68k-unknown-apple
ac_cv_target_alias=m68k-unknown-apple
EOF

  # Patch PCC local.c: it casts to (union flt *) but pass1.h defines
  # 'struct flt', not 'union flt' — this is a PCC bug causing a compile
  # error ("flt defined as wrong kind of tag") regardless of nativefp.
  sed -i 's/(union flt \*)/(struct flt *)/g' arch/m68k/local.c

  # Patch m68k macdefs.h: softfloat.c requires USE_IEEEFP_32/64/X80 to
  # define IEEE FP format descriptors.  i386/amd64 define these; m68k
  # backend never did.  Classic Mac uses IEEE 32/64 for float/double and
  # SANE 80-bit extended (closest to x80) for long double.
  printf '\n/* floating point definitions (required by softfloat.c) */\n#define USE_IEEEFP_32\n#define USE_IEEEFP_64\n#define USE_IEEEFP_X80\n' >> arch/m68k/macdefs.h

  ./configure --cache-file=config.cache --target=m68k-unknown-apple --disable-nativefp

  # GCC 10+ defaults to -fno-common: scan.l and common.c both declare
  # 'int lineno' as tentative definitions that used to merge; they now
  # conflict.  Restore the old behaviour for this vendored PCC build.
  sed -i 's/^CFLAGS = /CFLAGS = -fcommon /' cc/ccom/Makefile

  # Build only cc/ccom (the compiler proper).  The cc/cc driver wrapper
  # requires ccconfig.h which is not in the repo and not generated by
  # configure — we invoke ccom directly instead of via the driver.
  make -C cc/ccom -j"$(nproc 2>/dev/null || sysctl -n hw.ncpu)"
  popd > /dev/null
  echo "=== PCC ccom built ==="
}

# ── compile ────────────────────────────────────────────────────────────────
cmd_compile() {
  echo "=== Compiling hello.c with PCC ccom m68k backend ==="
  mkdir -p "${BUILD_DIR}"

  # Locate the ccom binary.  With BINPREFIX=m68k-unknown-apple-, the binary
  # is named m68k-unknown-apple-ccom (or just ccom in some builds).
  CCOM_BIN=$(find "${PCC_SRC}/cc/ccom" -name "*ccom" -type f 2>/dev/null | head -1)
  if [ -z "${CCOM_BIN}" ]; then
    echo "ERROR: ccom binary not found under ${PCC_SRC}/cc/ccom — did build-pcc succeed?"
    exit 1
  fi
  echo "Using ccom binary: ${CCOM_BIN}"

  # ccom is the compiler proper and expects preprocessed input.
  # Step 1: preprocess with the system C preprocessor.
  gcc -E \
    -I "${SPIKE_DIR}/../src/include" \
    "${SPIKE_DIR}/hello.c" \
    -o "${BUILD_DIR}/hello.i" \
    && echo "Preprocessing: OK" \
    || { echo "Preprocessing: FAILED"; exit 1; }

  # Step 2: compile preprocessed C to m68k assembly with PCC ccom.
  "${CCOM_BIN}" "${BUILD_DIR}/hello.i" "${BUILD_DIR}/hello.s" \
    && echo "PCC ccom compilation: OK" \
    || { echo "PCC ccom compilation: FAILED"; exit 1; }

  echo "--- Assembly output (first 60 lines) ---"
  head -60 "${BUILD_DIR}/hello.s"

  # Step 3: assemble the PCC output.
  # Use -m68020 because PCC emits 68020+ instructions (extb.l, muls.l, etc.).
  m68k-linux-gnu-as -m68020 -o "${BUILD_DIR}/hello.o" "${BUILD_DIR}/hello.s" \
    && echo "Assembly: OK" \
    || { echo "Assembly: FAILED (is m68k-linux-gnu-as installed?)"; exit 1; }

  # Step 4: assemble the minimal Phase 0 startup stub.
  m68k-linux-gnu-as -m68020 -o "${BUILD_DIR}/crt0_minimal.o" "${SPIKE_DIR}/crt0_minimal.s" \
    && echo "crt0 assembly: OK" \
    || { echo "crt0 assembly: FAILED"; exit 1; }

  # Step 5: link.
  # Phase 0 uses crt0_minimal.s (provides _start) instead of libretrocrt.a
  # to avoid undefined linker symbols from the full Retro68 CRT.
  # Phase 1 will link with libretrocrt.a + libc.a + libInterface.a.
  m68k-linux-gnu-ld \
    -m m68kelf \
    -T "${SPIKE_DIR}/mac.ld" \
    "${BUILD_DIR}/crt0_minimal.o" \
    "${BUILD_DIR}/hello.o" \
    -o "${BUILD_DIR}/hello.elf" \
    && echo "Linking: OK" \
    || { echo "Linking: FAILED — see symbol errors above"; exit 1; }

  echo "=== hello.elf produced at ${BUILD_DIR}/hello.elf ==="
}

# ── link ──────────────────────────────────────────────────────────────────
cmd_link() {
  echo "=== Phase 1: Linking hello.o → hello.bin via Retro68 Elf2Mac ==="

  # Elf2Mac is the Retro68 linker wrapper.  Calling it directly with
  # --mac-single produces a single-segment MacBinary (CODE 0 + CODE 1,
  # type=APPL, creator=????) without going through GCC, which has --mac-flat
  # baked into its specs and would produce a flat code resource instead.
  #
  # RETRO68_REAL_LD tells Elf2Mac where the real GNU ld lives (Elf2Mac
  # normally finds it by appending ".real" to argv[0]).
  #
  # Library order: -lretrocrt first (_start + relocator), then -lc
  # (atexit/exit referenced by libretrocrt.a start.c).  We skip -lgcc
  # because PCC emits native 68020 instructions (muls.l, divu.l) rather
  # than soft-math helpers.

  docker run --rm \
    -v "$(cd "${SPIKE_DIR}/.." && pwd)":/work \
    --entrypoint /bin/bash \
    "${RETRO68_IMAGE}" \
    -c "
      set -euo pipefail

      # Locate Elf2Mac and the real ld in the Docker image.
      # Known-good prefix from Phase 0 extraction: /Retro68-build/toolchain
      BINDIR=/Retro68-build/toolchain/bin
      ELF2MAC=\${BINDIR}/Elf2Mac
      REAL_LD=\${BINDIR}/m68k-apple-macos-ld.real
      LIBDIR=/Retro68-build/toolchain/m68k-apple-macos/lib

      # Fall back to a full search if the expected paths aren't present.
      if [ ! -x \"\${ELF2MAC}\" ]; then
        ELF2MAC=\$(find /usr/local -name 'Elf2Mac' -type f 2>/dev/null | head -1)
        BINDIR=\$(dirname \"\${ELF2MAC}\")
        REAL_LD=\${BINDIR}/m68k-apple-macos-ld.real
        LIBDIR=\$(dirname \"\${BINDIR}\")/m68k-apple-macos/lib
      fi

      # Fail explicitly if required paths are missing.
      test -x \"\${ELF2MAC}\" || { echo \"FAIL: Elf2Mac not found at \${ELF2MAC}\"; exit 1; }
      test -x \"\${REAL_LD}\"  || { echo \"FAIL: real ld not found at \${REAL_LD}\"; exit 1; }
      test -d \"\${LIBDIR}\"   || { echo \"FAIL: lib dir not found at \${LIBDIR}\"; exit 1; }

      echo \"Elf2Mac  : \${ELF2MAC}\"
      echo \"Real ld  : \${REAL_LD}\"
      echo \"Lib dir  : \${LIBDIR}\"

      # Library order for circular deps:
      #   libretrocrt: CRT startup; its malloc.c needs __mulsi3 (libgcc) and memcpy (libc);
      #                its syscalls.c needs Mac File Manager traps (libInterface).
      #   libgcc:      soft-math helpers (__mulsi3, __udivsi3) from Retro68's GCC-compiled libs.
      #   libInterface: ALL Mac Toolbox A-trap stubs; required by libretrocrt syscalls.
      #   Repeat -lretrocrt after -lc to resolve circular libc ↔ retrocrt deps.
      RETRO68_REAL_LD=\"\${REAL_LD}\" \"\${ELF2MAC}\" \
        --mac-single \
        -o /work/spike/build/hello.bin \
        /work/spike/build/hello.o \
        -L\"\${LIBDIR}\" \
        -lretrocrt -lc -lInterface -lgcc -lretrocrt

      echo 'Elf2Mac: OK'
    " \
    && echo "Phase 1 link: OK" \
    || { echo "Phase 1 link: FAILED"; exit 1; }

  echo "=== hello.bin produced at ${BUILD_DIR}/hello.bin ==="
  ls -lh "${BUILD_DIR}/hello.bin"
}

# ── verify ─────────────────────────────────────────────────────────────────
cmd_verify() {
  echo "=== Phase 1: Validating MacBinary format ==="
  local BIN="${BUILD_DIR}/hello.bin"

  if [ ! -f "${BIN}" ]; then
    echo "FAIL: hello.bin not found — run 'link' first"
    exit 1
  fi

  # MacBinary II header (128 bytes):
  #   byte   0     : version (0x00 for old/MacBinary II compatibility)
  #   bytes  1-64  : filename (Pascal string, byte 1 = length)
  #   bytes 65-68  : file type OSType ('APPL' = 0x41 0x50 0x50 0x4C)
  #   bytes 69-72  : creator OSType
  # We verify the APPL type field and that the file is at least 128 bytes.

  local FILE_SIZE
  FILE_SIZE=$(wc -c < "${BIN}")
  if [ "${FILE_SIZE}" -lt 128 ]; then
    echo "FAIL: hello.bin is ${FILE_SIZE} bytes — too small for MacBinary header"
    exit 1
  fi

  local FILE_TYPE
  FILE_TYPE=$(dd if="${BIN}" bs=1 skip=65 count=4 2>/dev/null | od -A n -t x1 | tr -d ' \n')
  if [ "${FILE_TYPE}" = "4150504c" ]; then
    echo "PASS: MacBinary type = APPL (${FILE_TYPE})"
  else
    echo "FAIL: MacBinary type = '${FILE_TYPE}' (expected 4150504c = APPL)"
    exit 1
  fi

  echo "=== MacBinary validation passed (${FILE_SIZE} bytes) ==="
}

# ── build-stubs ────────────────────────────────────────────────────────────
cmd_build_stubs() {
  echo "=== Phase 2: Assembling libtoolbox-stubs.a ==="
  local STUBS_S="${SPIKE_DIR}/../src/stubs/libtoolbox-stubs.s"
  local STUBS_O="${BUILD_DIR}/libtoolbox-stubs.o"
  local STUBS_A="${BUILD_DIR}/libtoolbox-stubs.a"

  [ -f "${STUBS_S}" ] || { echo "FAIL: ${STUBS_S} not found"; exit 1; }

  # Assemble with m68k-linux-gnu-as (same toolchain used for Phase 0/1).
  m68k-linux-gnu-as -m68020 "${STUBS_S}" -o "${STUBS_O}" \
    && echo "Assembled: OK" \
    || { echo "Assembly: FAILED"; exit 1; }

  # Archive into a static library.
  m68k-linux-gnu-ar rcs "${STUBS_A}" "${STUBS_O}" \
    && echo "Archived: ${STUBS_A}" \
    || { echo "Archive: FAILED"; exit 1; }

  echo "=== libtoolbox-stubs.a ready ==="
  m68k-linux-gnu-nm "${STUBS_A}" | grep " T " | awk '{print "  " $3}'
}

# ── compile-toolbox ─────────────────────────────────────────────────────────
cmd_compile_toolbox() {
  echo "=== Phase 2: Compiling hello_toolbox.c with PCC ccom m68k backend ==="
  local SRC="${SPIKE_DIR}/hello_toolbox.c"

  [ -f "${SRC}" ] || { echo "FAIL: ${SRC} not found"; exit 1; }

  # Locate ccom (same as cmd_compile).
  CCOM_BIN=$(find "${PCC_SRC}/cc/ccom" -name "*ccom" -type f 2>/dev/null | head -1)
  if [ -z "${CCOM_BIN}" ]; then
    echo "ERROR: ccom binary not found — did build-pcc succeed?"
    exit 1
  fi

  # Preprocess with the system C preprocessor.
  gcc -E \
    -I "${SPIKE_DIR}/../src/include" \
    "${SRC}" \
    -o "${BUILD_DIR}/hello_toolbox.i" \
    && echo "Preprocessing: OK" \
    || { echo "Preprocessing: FAILED"; exit 1; }

  # Compile to m68k assembly with PCC ccom.
  "${CCOM_BIN}" "${BUILD_DIR}/hello_toolbox.i" "${BUILD_DIR}/hello_toolbox.s" \
    && echo "PCC ccom compilation: OK" \
    || { echo "PCC ccom compilation: FAILED"; exit 1; }

  echo "--- Assembly output (first 60 lines) ---"
  head -60 "${BUILD_DIR}/hello_toolbox.s"

  # Assemble to ELF object.
  m68k-linux-gnu-as -m68020 \
    "${BUILD_DIR}/hello_toolbox.s" \
    -o "${BUILD_DIR}/hello_toolbox.o" \
    && echo "Assembly: OK" \
    || { echo "Assembly: FAILED"; exit 1; }

  echo "=== hello_toolbox.o produced ==="
  m68k-linux-gnu-nm "${BUILD_DIR}/hello_toolbox.o" | grep " [TU] " | head -20
}

# ── link-toolbox ────────────────────────────────────────────────────────────
cmd_link_toolbox() {
  echo "=== Phase 2: Linking hello_toolbox.o → hello_toolbox.bin via Elf2Mac ==="

  # Link order: toolbox stubs first (they resolve Toolbox references from hello_toolbox.o),
  # then retrocrt (_start, relocator), then libc (atexit/exit, called by retrocrt).
  docker run --rm \
    -v "$(cd "${SPIKE_DIR}/.." && pwd)":/work \
    --entrypoint /bin/bash \
    "${RETRO68_IMAGE}" \
    -c "
      set -euo pipefail

      BINDIR=/Retro68-build/toolchain/bin
      ELF2MAC=\${BINDIR}/Elf2Mac
      REAL_LD=\${BINDIR}/m68k-apple-macos-ld.real
      LIBDIR=/Retro68-build/toolchain/m68k-apple-macos/lib

      if [ ! -x \"\${ELF2MAC}\" ]; then
        ELF2MAC=\$(find /usr/local -name 'Elf2Mac' -type f 2>/dev/null | head -1)
        BINDIR=\$(dirname \"\${ELF2MAC}\")
        REAL_LD=\${BINDIR}/m68k-apple-macos-ld.real
        LIBDIR=\$(dirname \"\${BINDIR}\")/m68k-apple-macos/lib
      fi

      test -x \"\${ELF2MAC}\" || { echo \"FAIL: Elf2Mac not found at \${ELF2MAC}\"; exit 1; }
      test -x \"\${REAL_LD}\"  || { echo \"FAIL: real ld not found at \${REAL_LD}\"; exit 1; }
      test -d \"\${LIBDIR}\"   || { echo \"FAIL: lib dir not found at \${LIBDIR}\"; exit 1; }

      echo \"Elf2Mac  : \${ELF2MAC}\"
      echo \"Real ld  : \${REAL_LD}\"
      echo \"Lib dir  : \${LIBDIR}\"

      RETRO68_REAL_LD=\"\${REAL_LD}\" \"\${ELF2MAC}\" \
        --mac-single \
        -o /work/spike/build/hello_toolbox.bin \
        /work/spike/build/hello_toolbox.o \
        /work/spike/build/libtoolbox-stubs.a \
        -L\"\${LIBDIR}\" \
        -lretrocrt -lc -lInterface -lgcc -lretrocrt

      echo 'Elf2Mac (toolbox): OK'
    " \
    && echo "Phase 2 link: OK" \
    || { echo "Phase 2 link: FAILED"; exit 1; }

  echo "=== hello_toolbox.bin produced ==="
  ls -lh "${BUILD_DIR}/hello_toolbox.bin"
}

# ── verify-toolbox ──────────────────────────────────────────────────────────
cmd_verify_toolbox() {
  echo "=== Phase 2: Validating hello_toolbox MacBinary format ==="
  local BIN="${BUILD_DIR}/hello_toolbox.bin"

  if [ ! -f "${BIN}" ]; then
    echo "FAIL: hello_toolbox.bin not found — run 'link-toolbox' first"
    exit 1
  fi

  local FILE_SIZE
  FILE_SIZE=$(wc -c < "${BIN}")
  if [ "${FILE_SIZE}" -lt 128 ]; then
    echo "FAIL: hello_toolbox.bin is ${FILE_SIZE} bytes — too small for MacBinary header"
    exit 1
  fi

  local FILE_TYPE
  FILE_TYPE=$(dd if="${BIN}" bs=1 skip=65 count=4 2>/dev/null | od -A n -t x1 | tr -d ' \n')
  if [ "${FILE_TYPE}" = "4150504c" ]; then
    echo "PASS: MacBinary type = APPL (${FILE_TYPE})"
  else
    echo "FAIL: MacBinary type = '${FILE_TYPE}' (expected 4150504c = APPL)"
    exit 1
  fi

  echo "=== MacBinary validation passed (${FILE_SIZE} bytes) ==="
}

# ── compare ───────────────────────────────────────────────────────────────
# NOTE: This command is NOT run in CI (spike.yml). It is provided for local
# comparison only. It requires Docker and that 'compile' has already run.
cmd_compare() {
  echo "=== Building reference with Retro68 GCC (via Docker) ==="
  docker run --rm \
    -v "${SPIKE_DIR}:/spike" \
    "${RETRO68_IMAGE}" \
    bash -c "
      cd /tmp && mkdir ref && cd ref
      cp /spike/hello.c .
      cat > CMakeLists.txt << 'EOF'
cmake_minimum_required(VERSION 3.15)
project(HelloSpike C)
add_application(HelloSpike CREATOR ???? hello.c)
EOF
      cmake . -DCMAKE_TOOLCHAIN_FILE=/Retro68-build/toolchain/m68k-apple-macos/cmake/retro68.toolchain.cmake
      cmake --build .
      cp HelloSpike.bin /spike/build/hello-retro68.bin
    "

  echo "=== Comparison ==="
  echo "PCC output size:     $(wc -c < "${BUILD_DIR}/hello.elf" 2>/dev/null || echo 'NOT BUILT')"
  echo "Retro68 output size: $(wc -c < "${BUILD_DIR}/hello-retro68.bin" 2>/dev/null || echo 'NOT BUILT')"
  echo ""
  echo "Symbol diff (PCC output):"
  nm "${BUILD_DIR}/hello.elf" 2>/dev/null | sort || true
  echo ""
  echo "NOTE: Sizes will differ (ELF vs MacBinary) but symbol names should match."
  echo "If PCC output has undefined symbols that Retro68 reference resolves, those"
  echo "are missing from our shim headers or stub archive."
}

# ── dispatch ──────────────────────────────────────────────────────────────
case "${1:-all}" in
  setup)            cmd_setup ;;
  build-pcc)        cmd_build_pcc ;;
  compile)          cmd_compile ;;
  link)             cmd_link ;;
  verify)           cmd_verify ;;
  build-stubs)      cmd_build_stubs ;;
  compile-toolbox)  cmd_compile_toolbox ;;
  link-toolbox)     cmd_link_toolbox ;;
  verify-toolbox)   cmd_verify_toolbox ;;
  compare)          cmd_compare ;;
  all)
    cmd_setup && cmd_build_pcc \
      && cmd_compile && cmd_link && cmd_verify \
      && cmd_build_stubs && cmd_compile_toolbox && cmd_link_toolbox && cmd_verify_toolbox \
      && cmd_compare
    ;;
  *)
    echo "Usage: $0 [setup|build-pcc|compile|link|verify|build-stubs|compile-toolbox|link-toolbox|verify-toolbox|compare|all]"
    exit 1
    ;;
esac
