#!/usr/bin/env bash
# spike/run-spike.sh — Phase 0 feasibility script
#
# Tests whether PCC's m68k backend produces output that can be linked
# against pre-compiled Retro68 stubs and produce a bootable Mac binary.
#
# Usage:
#   bash spike/run-spike.sh setup      # extract Retro68 stubs from Docker and clone PCC
#   bash spike/run-spike.sh build-pcc  # build PCC for m68k code generation
#   bash spike/run-spike.sh compile    # compile hello.c with native PCC
#   bash spike/run-spike.sh compare    # compare against Retro68 reference output
#   bash spike/run-spike.sh all        # run setup, build-pcc, compile, compare

set -euo pipefail
SPIKE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PCC_SRC="${SPIKE_DIR}/pcc-src"      # git clone of PCC goes here
STUBS_DIR="${SPIKE_DIR}/retro68-stubs"
HEADERS_DIR="${SPIKE_DIR}/retro68-headers"
BUILD_DIR="${SPIKE_DIR}/build"
RETRO68_IMAGE="ghcr.io/autc04/retro68:latest"

# ── setup ──────────────────────────────────────────────────────────────────
cmd_setup() {
  echo "=== Extracting Retro68 stubs from Docker image ==="
  docker pull "${RETRO68_IMAGE}"
  mkdir -p "${STUBS_DIR}" "${HEADERS_DIR}"

  # Use --entrypoint /bin/bash to bypass the Retro68 docker-entrypoint.sh,
  # which prints "Using multiversal interfaces" to stdout and corrupts the
  # tar stream when piped.  tar -h dereferences symlinks (libInterface.a
  # is a relative symlink pointing outside the lib/ directory).
  docker run --rm --entrypoint /bin/bash "${RETRO68_IMAGE}" \
    -c 'tar -hcf - -C /Retro68-build/toolchain/m68k-apple-macos lib' \
    | tar -xf - --strip-components=1 -C "${STUBS_DIR}"

  docker run --rm --entrypoint /bin/bash "${RETRO68_IMAGE}" \
    -c 'tar -hcf - -C /Retro68-build/toolchain/m68k-apple-macos include' \
    | tar -xf - --strip-components=1 -C "${HEADERS_DIR}"

  echo "Stubs extracted to: ${STUBS_DIR}"
  echo "Headers extracted to: ${HEADERS_DIR}"

  if [ ! -d "${PCC_SRC}" ]; then
    echo "=== Cloning PCC ==="
    git clone https://github.com/IanHarvey/pcc "${PCC_SRC}"
  fi
}

# ── build-pcc ──────────────────────────────────────────────────────────────
cmd_build_pcc() {
  echo "=== Building PCC ccom for m68k code generation ==="
  pushd "${PCC_SRC}" > /dev/null

  # PCC's configure.ac maps target_os=apple → abi=classic68k → m68k backend.
  # config.sub (2015) treats 'apple' as a vendor alias (not OS) and rejects
  # the triple before configure.ac runs.  Pre-populate config.cache so
  # AC_CANONICAL_TARGET uses the cached values and skips config.sub.
  BUILD_TRIPLE=$(gcc -dumpmachine 2>/dev/null || echo "x86_64-unknown-linux-gnu")
  cat > config.cache << EOF
ac_cv_build=${BUILD_TRIPLE}
ac_cv_build_alias=${BUILD_TRIPLE}
ac_cv_host=${BUILD_TRIPLE}
ac_cv_host_alias=${BUILD_TRIPLE}
ac_cv_target=m68k-unknown-apple
ac_cv_target_alias=m68k-unknown-apple
EOF

  # Patch PCC local.c: it casts to (union flt *) but pass1.h defines
  # 'struct flt', not 'union flt' — this is a PCC bug causing a compile
  # error ("flt defined as wrong kind of tag") regardless of nativefp.
  sed -i 's/(union flt \*)/(struct flt *)/g' arch/m68k/local.c

  # Patch m68k macdefs.h: softfloat.c requires USE_IEEEFP_32/64/X80 to
  # define IEEE FP format descriptors.  i386/amd64 define these; m68k
  # backend never did.  Classic Mac uses IEEE 32/64 for float/double and
  # SANE 80-bit extended (closest to x80) for long double.
  printf '\n/* floating point definitions (required by softfloat.c) */\n#define USE_IEEEFP_32\n#define USE_IEEEFP_64\n#define USE_IEEEFP_X80\n' >> arch/m68k/macdefs.h

  ./configure --cache-file=config.cache --target=m68k-unknown-apple --disable-nativefp

  # Build only cc/ccom (the compiler proper).  The cc/cc driver wrapper
  # requires ccconfig.h which is not in the repo and not generated by
  # configure — we invoke ccom directly instead of via the driver.
  make -C cc/ccom -j"$(nproc 2>/dev/null || sysctl -n hw.ncpu)"
  popd > /dev/null
  echo "=== PCC ccom built ==="
}

# ── compile ────────────────────────────────────────────────────────────────
cmd_compile() {
  echo "=== Compiling hello.c with PCC ccom m68k backend ==="
  mkdir -p "${BUILD_DIR}"

  # Locate the ccom binary.  With BINPREFIX=m68k-unknown-apple-, the binary
  # is named m68k-unknown-apple-ccom (or just ccom in some builds).
  CCOM_BIN=$(find "${PCC_SRC}/cc/ccom" -name "*ccom" -type f 2>/dev/null | head -1)
  if [ -z "${CCOM_BIN}" ]; then
    echo "ERROR: ccom binary not found under ${PCC_SRC}/cc/ccom — did build-pcc succeed?"
    exit 1
  fi
  echo "Using ccom binary: ${CCOM_BIN}"

  # ccom is the compiler proper and expects preprocessed input.
  # Step 1: preprocess with the system C preprocessor.
  gcc -E \
    -I "${SPIKE_DIR}/../src/include" \
    "${SPIKE_DIR}/hello.c" \
    -o "${BUILD_DIR}/hello.i" \
    && echo "Preprocessing: OK" \
    || { echo "Preprocessing: FAILED"; exit 1; }

  # Step 2: compile preprocessed C to m68k assembly with PCC ccom.
  "${CCOM_BIN}" "${BUILD_DIR}/hello.i" "${BUILD_DIR}/hello.s" \
    && echo "PCC ccom compilation: OK" \
    || { echo "PCC ccom compilation: FAILED"; exit 1; }

  echo "--- Assembly output (first 60 lines) ---"
  head -60 "${BUILD_DIR}/hello.s"

  # Step 3: assemble the PCC output.
  # Use -m68020 because PCC emits 68020+ instructions (extb.l, muls.l, etc.).
  m68k-linux-gnu-as -m68020 -o "${BUILD_DIR}/hello.o" "${BUILD_DIR}/hello.s" \
    && echo "Assembly: OK" \
    || { echo "Assembly: FAILED (is m68k-linux-gnu-as installed?)"; exit 1; }

  # Step 4: assemble the minimal Phase 0 startup stub.
  m68k-linux-gnu-as -m68020 -o "${BUILD_DIR}/crt0_minimal.o" "${SPIKE_DIR}/crt0_minimal.s" \
    && echo "crt0 assembly: OK" \
    || { echo "crt0 assembly: FAILED"; exit 1; }

  # Step 5: link.
  # Phase 0 uses crt0_minimal.s (provides _start) instead of libretrocrt.a
  # to avoid undefined linker symbols from the full Retro68 CRT.
  # Phase 1 will link with libretrocrt.a + libc.a + libInterface.a.
  m68k-linux-gnu-ld \
    -m m68kelf \
    -T "${SPIKE_DIR}/mac.ld" \
    "${BUILD_DIR}/crt0_minimal.o" \
    "${BUILD_DIR}/hello.o" \
    -o "${BUILD_DIR}/hello.elf" \
    && echo "Linking: OK" \
    || { echo "Linking: FAILED — see symbol errors above"; exit 1; }

  echo "=== hello.elf produced at ${BUILD_DIR}/hello.elf ==="
}

# ── compare ───────────────────────────────────────────────────────────────
cmd_compare() {
  echo "=== Building reference with Retro68 GCC (via Docker) ==="
  docker run --rm \
    -v "${SPIKE_DIR}:/spike" \
    "${RETRO68_IMAGE}" \
    bash -c "
      cd /tmp && mkdir ref && cd ref
      cp /spike/hello.c .
      cat > CMakeLists.txt << 'EOF'
cmake_minimum_required(VERSION 3.15)
project(HelloSpike C)
add_application(HelloSpike CREATOR ???? hello.c)
EOF
      cmake . -DCMAKE_TOOLCHAIN_FILE=/Retro68-build/toolchain/m68k-apple-macos/cmake/retro68.toolchain.cmake
      cmake --build .
      cp HelloSpike.bin /spike/build/hello-retro68.bin
    "

  echo "=== Comparison ==="
  echo "PCC output size:     $(wc -c < "${BUILD_DIR}/hello.elf" 2>/dev/null || echo 'NOT BUILT')"
  echo "Retro68 output size: $(wc -c < "${BUILD_DIR}/hello-retro68.bin" 2>/dev/null || echo 'NOT BUILT')"
  echo ""
  echo "Symbol diff (PCC output):"
  nm "${BUILD_DIR}/hello.elf" 2>/dev/null | sort || true
  echo ""
  echo "NOTE: Sizes will differ (ELF vs MacBinary) but symbol names should match."
  echo "If PCC output has undefined symbols that Retro68 reference resolves, those"
  echo "are missing from our shim headers or stub archive."
}

# ── dispatch ──────────────────────────────────────────────────────────────
case "${1:-all}" in
  setup)     cmd_setup ;;
  build-pcc) cmd_build_pcc ;;
  compile)   cmd_compile ;;
  compare)   cmd_compare ;;
  all)       cmd_setup && cmd_build_pcc && cmd_compile && cmd_compare ;;
  *)         echo "Usage: $0 [setup|build-pcc|compile|compare|all]"; exit 1 ;;
esac
